import { NextResponse } from "next/server";
import { envValue } from "@/lib/env";
import { requireAdmin } from "@/lib/server/session";
import { runRefresh } from "@/lib/server/refresh-job";
import { settlePending } from "@/lib/ledger/settle";
import { runLearning } from "@/lib/ledger/learn";
import { sendDailyDigest } from "@/lib/server/telegram";
import { safeEqual } from "@/lib/server/auth";
import { logEvent, reportError } from "@/lib/server/ops-log";
import { runFeatured } from "@/lib/server/featured";
import { settleBankrollLegs } from "@/lib/server/bankroll";
import { runLineupWatch } from "@/lib/server/lineups";
import { runCloseJob } from "@/lib/server/leg-prices";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The scheduler's entry point. `job` picks what runs:
 *   settle  — grade every finished game's tickets (ESPN only, no tokens); hourly
 *   digest  — "seus bilhetes de hoje" to Telegram subscribers; safe to call every tick, sends once a day
 *   learn   — post-mortem over the last 24h of settled tickets, proposes a prompt change; daily
 *   featured — "destaques do dia": up to FEATURED_PER_DAY games generated by the system (also runs
 *             before every refresh tick, whatever CRON_ENABLED says)
 *   lineups — vigia de escalação: pending tickets starting within 100 min vs the lineup/injuries; every tick
 *   close   — CLV: the closing price of every pending leg whose game starts within 15 min; every tick
 *   refresh — background generation (off unless CRON_ENABLED=1); every 4h
 * Protected by the x-cron-secret header (constant-time compare), or by an admin session for manual
 * runs from the panel. Every run logs one JSON summary line for `docker compose logs`.
 */
export async function POST(request: Request) {
  const url = new URL(request.url);
  const secret = envValue("CRON_SECRET");
  const provided = request.headers.get("x-cron-secret");
  const byCron = !!secret && safeEqual(provided, secret);
  if (!byCron && !(await requireAdmin())) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const job = url.searchParams.get("job") ?? "refresh";
  const started = Date.now();
  try {
    if (job === "settle") {
      const result = await settlePending(500);
      const bankroll = await settleBankrollLegs().catch((error) => { reportError("job.settle.bankroll", error); return null; });
      logEvent("job.settle", { ...result, bankroll, ms: Date.now() - started });
      return NextResponse.json({ job, ...result, bankroll });
    }
    if (job === "digest") {
      const date = url.searchParams.get("date") ?? undefined;
      const result = await sendDailyDigest({ dateKey: date, force: url.searchParams.get("force") === "1" || !!date });
      logEvent("job.digest", { ...result, ms: Date.now() - started });
      return NextResponse.json({ job, ...result });
    }
    if (job === "learn") {
      const hours = Number(url.searchParams.get("hours") ?? "24");
      const run = await runLearning({ sinceHours: Number.isFinite(hours) ? hours : 24 });
      logEvent("job.learn", { id: run?.id, status: run?.status, tickets: run?.tickets, ms: Date.now() - started });
      if (run?.status === "error") reportError("job.learn", new Error(run.note || "learning run failed"), { id: run.id });
      return NextResponse.json({ job, run });
    }
    if (job === "lineups") {
      const result = await runLineupWatch();
      return NextResponse.json({ job, ...result });
    }
    if (job === "close") {
      const result = await runCloseJob();
      return NextResponse.json({ job, ...result });
    }
    if (job === "featured") {
      const result = await runFeatured();
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    // The featured games are the product's floor: they run on the refresh tick even with the full
    // background refresh switched off.
    const featured = await runFeatured().catch((error) => { reportError("job.featured", error); return null; });
    const sports = (url.searchParams.get("sports") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    const maxGames = url.searchParams.get("maxGames") ? Number(url.searchParams.get("maxGames")) : undefined;
    const result = await runRefresh({ sports, maxGames: Number.isFinite(maxGames) ? maxGames : undefined });
    return NextResponse.json({ job, ...result, featured }, { status: result.status === "error" ? 500 : 200 });
  } catch (error) {
    reportError(`job.${job}`, error);
    return NextResponse.json({ error: `${job} failed` }, { status: 502 });
  }
}
