import { NextResponse } from "next/server";
import { envValue } from "@/lib/env";
import { requireAdmin } from "@/lib/server/session";
import { runRefresh } from "@/lib/server/refresh-job";
import { settlePending } from "@/lib/ledger/settle";
import { runLearning } from "@/lib/ledger/learn";
import { sendDailyDigest } from "@/lib/server/telegram";
import { safeEqual } from "@/lib/server/auth";
import { logEvent, reportError } from "@/lib/server/ops-log";
import { runFeatured } from "@/lib/server/featured";
import { runQuarterReads } from "@/lib/server/live-read";
import { runLocaliseBackfill } from "@/lib/server/localise-backfill";
import { runDayRecap } from "@/lib/server/day-recap";
import { settleBankrollLegs } from "@/lib/server/bankroll";
import { runLineupWatch } from "@/lib/server/lineups";
import { runCloseJob } from "@/lib/server/leg-prices";
import { runWeeklyReports } from "@/lib/server/weekly-report";
import { cleanupEvents } from "@/lib/server/analytics-report";
import { runBooksJob, runLiveBooksJob } from "@/lib/server/book-prices";
import { runTodayJob } from "@/lib/server/daily-list";
import { runAttributeJob } from "@/lib/server/factors-job";
import { runEvaluateJob } from "@/lib/server/evaluate-job";
import { onceADay } from "@/lib/server/job-guard";
import { runCrossDaily } from "@/lib/server/cross-daily";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The scheduler's entry point. `job` picks what runs:
 *   settle  — grade every finished game's tickets (ESPN only, no tokens); hourly
 *   digest  — "seus bilhetes de hoje" to Telegram subscribers; safe to call every tick, sends once a day
 *   learn   — post-mortem over the last 24h of settled tickets, proposes a prompt change; called every
 *             tick, runs once a Brasília day (the database decides, not a tick counter)
 *   evaluate — before/after of every applied hypothesis, writing its verdict (no tokens); once a day
 *   featured — "destaques do dia": up to FEATURED_PER_DAY games generated by the system (also runs
 *             before every refresh tick, whatever CRON_ENABLED says)
 *   attribute — which leg killed each ticket, and the calibration of every factor with a sample
 *             (no tokens, idempotent); every tick, right after settle
 *   today   — "os bilhetes de hoje": the day's short list and its stakes, from inventory that already
 *             exists (no generation, no tokens); every tick
 *   cross   — "as múltiplas do dia entre jogos": one cross-game slate per sport with two upcoming
 *             games or more, in the short window of bets/cross-policy.ts; called every tick, runs
 *             once a Brasília day (job_runs decides, not a tick counter)
 *   lineups — vigia de escalação: pending tickets starting within 100 min vs the lineup/injuries; every tick
 *   close   — CLV: the closing price of every pending leg whose game starts within 30 min; every tick
 *   weekly  — relatório semanal de disciplina; safe every tick, writes on Mondays from 12:00 UTC (force=1 to run now)
 *   cleanup — deletes analytics events older than 180 days; daily
 *   books   — Brazilian books' prices for every game in the next 48 h (pre-game only); every tick
 *   live-books — the IN-PLAY board of every game under way, from the books that serve one to a plain
 *             client (Superbet, KTO, the Altenar tenants); every tick, and as often as the scheduler
 *             can afford, because a live price is worth nothing a minute later
 *   refresh — background generation (off unless CRON_ENABLED=1); every 4h
 * Protected by the x-cron-secret header (constant-time compare), or by an admin session for manual
 * runs from the panel. Every run logs one JSON summary line for `docker compose logs`.
 */
export async function POST(request: Request) {
  const url = new URL(request.url);
  const secret = envValue("CRON_SECRET");
  const provided = request.headers.get("x-cron-secret");
  const byCron = !!secret && safeEqual(provided, secret);
  if (!byCron && !(await requireAdmin())) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const job = url.searchParams.get("job") ?? "refresh";
  const started = Date.now();
  try {
    if (job === "settle") {
      const result = await settlePending(500);
      const bankroll = await settleBankrollLegs().catch((error) => { reportError("job.settle.bankroll", error); return null; });
      logEvent("job.settle", { ...result, bankroll, ms: Date.now() - started });
      return NextResponse.json({ job, ...result, bankroll });
    }
    if (job === "digest") {
      const date = url.searchParams.get("date") ?? undefined;
      const result = await sendDailyDigest({ dateKey: date, force: url.searchParams.get("force") === "1" || !!date });
      logEvent("job.digest", { ...result, ms: Date.now() - started });
      return NextResponse.json({ job, ...result });
    }
    if (job === "learn") {
      // Called every tick and gated on the database, not on a tick counter held in the scheduler's
      // shell: `t` reset with every container restart, so the runs of the deploy days never fired.
      const hours = Number(url.searchParams.get("hours") ?? "24");
      const force = url.searchParams.get("force") === "1";
      const once = await onceADay("learn", () => runLearning({ sinceHours: Number.isFinite(hours) ? hours : 24 }), { force });
      const run = once.result;
      logEvent("job.learn", { id: run?.id, status: run?.status ?? "already_ran", tickets: run?.tickets, ran: once.ran, ms: Date.now() - started });
      if (run?.status === "error") reportError("job.learn", new Error(run.note || "learning run failed"), { id: run.id });
      return NextResponse.json({ job, ran: once.ran, note: once.note, run });
    }
    if (job === "evaluate") {
      // Did the applied rules help? Arithmetic over the ledger, zero tokens, once a day.
      const force = url.searchParams.get("force") === "1";
      const once = await onceADay("evaluate", () => runEvaluateJob(), { force });
      logEvent("job.evaluate", { ...(once.result ?? {}), ran: once.ran, ms: Date.now() - started });
      return NextResponse.json({ job, ran: once.ran, note: once.note, ...(once.result ?? {}) });
    }
    if (job === "attribute") {
      // Blame per leg and the factor report, both rebuilt from the ledger. Zero tokens, idempotent.
      const result = runAttributeJob();
      logEvent("job.attribute", { ...result, ms: Date.now() - started });
      return NextResponse.json({ job, ...result });
    }
    if (job === "today") {
      // The day's short list. Zero tokens, idempotent, and it rewrites the stored answer only when
      // the content hash changes — so a reader never watches the list flicker between equal answers.
      const result = runTodayJob();
      logEvent("job.today", { ...result, ms: Date.now() - started });
      return NextResponse.json({ job, ...result });
    }
    if (job === "cross") {
      // The day's múltiplas entre jogos. Called every tick and gated on the database, like learn and
      // evaluate: a counter in the scheduler's shell resets with the container and loses deploy days.
      const force = url.searchParams.get("force") === "1";
      const sports = (url.searchParams.get("sports") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
      const once = await onceADay("cross", () => runCrossDaily({ sports }), { force });
      const run = once.result;
      logEvent("job.cross", { ran: once.ran, generated: run?.generated, tickets: run?.tickets, costUsd: run?.costUsd, ms: Date.now() - started });
      return NextResponse.json({ job, ran: once.ran, note: once.note, ...(run ?? {}) }, { status: run?.status === "error" ? 500 : 200 });
    }
    if (job === "lineups") {
      const result = await runLineupWatch();
      return NextResponse.json({ job, ...result });
    }
    if (job === "close") {
      const result = await runCloseJob();
      return NextResponse.json({ job, ...result });
    }
    if (job === "weekly") {
      const result = await runWeeklyReports({ force: url.searchParams.get("force") === "1" });
      return NextResponse.json({ job, ...result });
    }
    if (job === "cleanup") {
      const deleted = cleanupEvents();
      logEvent("job.cleanup", { deleted, ms: Date.now() - started });
      return NextResponse.json({ job, deleted });
    }
    if (job === "books") {
      const sports = (url.searchParams.get("sports") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
      const result = await runBooksJob({ sports });
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    if (job === "live-books") {
      const sports = (url.searchParams.get("sports") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
      const result = await runLiveBooksJob({ sports });
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    if (job === "featured") {
      const result = await runFeatured();
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    if (job === "quarters") {
      const result = await runQuarterReads();
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    if (job === "localise") {
      const result = await runLocaliseBackfill();
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    if (job === "recap") {
      const result = await runDayRecap();
      return NextResponse.json({ job, ...result }, { status: result.status === "error" ? 500 : 200 });
    }
    // A mistyped job name must never fall through to generation.
    if (job !== "refresh") return NextResponse.json({ error: "unknown job" }, { status: 400 });
    // The featured games are the product's floor: they run on the refresh tick even with the full
    // background refresh switched off.
    const featured = await runFeatured().catch((error) => { reportError("job.featured", error); return null; });
    const sports = (url.searchParams.get("sports") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    const maxGames = url.searchParams.get("maxGames") ? Number(url.searchParams.get("maxGames")) : undefined;
    const result = await runRefresh({ sports, maxGames: Number.isFinite(maxGames) ? maxGames : undefined });
    return NextResponse.json({ job, ...result, featured }, { status: result.status === "error" ? 500 : 200 });
  } catch (error) {
    reportError(`job.${job}`, error);
    return NextResponse.json({ error: `${job} failed` }, { status: 502 });
  }
}
