"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Empty, Panel } from "@/components/ui";

interface Payload {
  games: { gameId: string; sportKey: string; rank: number; matchup: string; startsAt: string | null }[];
  costUsd: number;
  config: { perDay: number; sports: string[] };
  lastRun: { status: string; startedAt: string; note: string; costUsd: number; predictionsWritten: number } | null;
}

const dt = (iso: string | null) => (iso ? new Date(iso).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" }) : "—");

/** Destaques de hoje: the games the system generated by itself, with a manual trigger. */
export function AdminFeatured() {
  const [data, setData] = useState<Payload | null>(null);
  const [running, setRunning] = useState(false);
  const [note, setNote] = useState("");
  const load = useCallback(async () => {
    const r = await fetch("/api/admin/featured", { cache: "no-store" });
    if (r.ok) setData(await r.json());
  }, []);
  useEffect(() => { void (async () => { await Promise.resolve(); await load(); })(); }, [load]);

  async function run() {
    setRunning(true);
    setNote("");
    try {
      const r = await fetch("/api/admin/featured", { method: "POST" });
      const j = await r.json().catch(() => ({}));
      setNote(`${j.status ?? "erro"}: ${j.generated ?? 0} gerados, ${j.picked ?? 0} escolhidos. ${j.note ?? ""}`);
      await load();
    } finally {
      setRunning(false);
    }
  }

  return (
    <Panel
      title="Destaques de hoje"
      meta={data ? `${data.games.length}/${data.config.perDay} · $${data.costUsd.toFixed(2)} hoje` : undefined}
      action={<button onClick={() => void run()} disabled={running} data-testid="featured-run" className="rounded-md bg-signal-500 px-2.5 py-1 text-[12px] font-medium text-ink-950 disabled:opacity-50">{running ? "Gerando…" : "Gerar agora"}</button>}
    >
      <div data-testid="admin-featured">
        {note && <p className="mb-2 text-[12px] text-signal-400">{note}</p>}
        {data?.lastRun && (
          <p className={`mb-2 text-[12px] ${data.lastRun.status === "error" ? "text-alert-400" : "text-mist-400"}`} data-testid="featured-last-run">
            Última execução {dt(data.lastRun.startedAt)}: {data.lastRun.status} · {data.lastRun.predictionsWritten} predições · {data.lastRun.note || "—"}
          </p>
        )}
        {data?.games.length ? (
          <ul className="flex flex-col divide-y divide-ink-800 text-[13px]">
            {data.games.map((g) => (
              <li key={g.gameId} className="flex flex-wrap items-center gap-3 py-1.5">
                <span className="nums text-mist-500">#{g.rank + 1}</span>
                <Link href={`/app/game/${g.gameId}?sport=${g.sportKey}`} className="text-mist-100 hover:underline">{g.matchup || g.gameId}</Link>
                <span className="text-mist-500">{g.sportKey} · {dt(g.startsAt)}</span>
              </li>
            ))}
          </ul>
        ) : <Empty>Nenhum destaque hoje ainda. Esportes: {data?.config.sports.join(", ") ?? "—"}.</Empty>}
      </div>
    </Panel>
  );
}
